### ISSUE TITLE
using Wuyu.Epub;

### ISSUE THREAD

**Issue by jkl010** [LightNovelShelf/EbookReader-Xamarin#8]
using Wuyu.Epub;
作者您好，这个epub编译器缺少文件，下载了编译不过去啊，这个是自己建个目录放个epub文件吗？

**Comment by jkl010** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
警告		The referenced project '..\..\EpubBook\Wuyu.Epub\Wuyu.Epub.csproj' does not exist.	EbookReader

**Comment by wuyu8512** [comment]
缺少我另外一个开源项目的引用，发行版就有最新的，不需要自己编译
